--[==[badge-app
slug=htn_bump_pets
name=Bump Pets
icon=BUMP
api=2
heap_kb=96
wake_lock=1
]==]

-- Bump Pets -- the people you meet paint the picture behind your pet.
-- Every Connect contact adds brush strokes to the backdrop; your badge id
-- picks the species.  Everyone starts as an egg and hatches on their next
-- bump, however many contacts they already had.
-- L/R who is who   A rescan   B lights   Up/Dn brightness   HOME exit
--
-- READ BEFORE EDITING.  This badge raises "Lua stack safety limit reached"
-- when one callback does too much.  The vendor guide's remedy for that exact
-- message is "use an explicit bounded work queue", so on_enter does almost
-- nothing: it draws a loading label and returns.  All real work happens one
-- small step per on_tick, driven by P.step.  ONE contact is hashed per tick;
-- at most EIGHT widgets are created or styled per tick.
--
-- Do not move work back into on_enter.  Do not wrap string.byte in a loop.
-- Keep state in these tables, not in file-level locals: each local costs a
-- main-chunk slot and an upvalue in every function that reads it.
-- Verify with:  .\check.ps1

-- Built in separate statements on purpose: one big nested constructor makes
-- the main chunk reserve a register per element, which pushed it to 26 slots
-- and into stack-safety territory. Each statement below peaks on its own.
local C = {SCAN = 200, MAXS = 120, BG = 0x0b0f14}
-- Bumps that unlock the starfield leds. SET THIS TO 25 FOR THE EVENT; it is
-- low now so the effect can be tested without first meeting 25 people.
C.STAR = 5
-- Strokes painted however tight the heap is. See the budget in step 3.
C.MINS = 24
C.CW = {1, 2, 3, 4, 5, 6}
C.AT = {1, 2, 3, 5, 7, 10, 14, 19, 25, 32, 40, 50}
-- name, ear w, ear h, ear radius, ear spread, tail -- all as 34ths of the
-- head width, so the whole animal scales with one number
C.SP = {}
C.SP[1] = {"Bun",   7, 17, 17, 10, 5}
C.SP[2] = {"Cat",   9,  9,  3, 12, 4}
C.SP[3] = {"Bear", 10, 10, 10, 13, 3}
C.SP[4] = {"Fox",   9, 13,  3, 13, 7}
-- Every box the creature is made of, in the order they are created, which
-- is the order they stack in. Index 1 is the egg; the rest are the animal.
C.MK = {"egg", "tail", "tailT", "body", "belly", "footL", "footR",
        "earL", "earR", "einL", "einR", "head", "blL", "blR",
        "eyeL", "eyeR", "glL", "glR", "nose"}
-- generated by tools/artgen.py from night.png: 12 colours, 120 strokes
C.PAL = {0x0c1246, 0x24253a, 0x3a589f, 0x282738, 0x7b899c, 0x153a3d,
         0x202240, 0x36436d, 0x0f2c32, 0x181b42, 0x2c2e45, 0x202e44}
C.ART = "ABCDEFGABABCFGABHFHIGADCFJIHAKGDGFGABKDCFGABKFJILFBHDEFLIBADCFGIBJBCDKFHLDJICFKADJFJIGABCLHIGABJDCFGABEFCIGABCFJIHABCDHF"

local S = {
  total = 0, stage = 0,
  newest = "", petname = "PET", species = 1,
  pr = 255, pg = 190, pb = 90,
  nextf = 0, celeb = 0, blink = false,
  led = true, lv = 170,
  seen = -1, dirty = false,
  -- hatch is the contact count the egg was armed at, stored on the first
  -- open. Everyone hatches on their NEXT bump, however many contacts they
  -- already had. egg is derived from it on every scan.
  hatch = -1, egg = true,
  -- ns strokes are painted, k of them per contact. cur is the contact the
  -- attribution cursor is on, 0 for none; nm is a ring of names.
  cur = 0, sel = 0, base = 0, poff = 0, nm = {},
  -- nlo is the first stroke a newly met contact painted, 0 for none;
  -- npul is the border width currently on them, so the pulse only
  -- restyles on a change rather than every frame.
  nlo = 0, npul = 0,
}

-- progress of the bounded work queue.  step 0 means ready.
local P = {step = 1, i = 1, fold = 7, n = 0, k = 1, made = false}

local W = {}   -- named widgets
local G = {}   -- brush strokes, back to front
local L = {}   -- precomputed layout, so draw() only adds the bob

-- Size and colour one box. Nineteen copies of these three lines was the
-- single largest block in the file.
C.pw = function(n, w, h, c, r)
  local x = W[n]
  x:set_size(w, h)
  x:style({bg_color = c, radius = r, border_width = 0})
end

-- Coats are restricted to 12..57 degrees, the red-to-yellow arc, so five
-- sixths of the colour wheel were unreachable once the celebration stopped
-- using it. A caller outside that range gets a wrong colour, not an error.
local function hue(x)
  local u = (200 * (x % 60)) // 60 + 55
  return 255, u, 55
end

local function hex(r, g, b) return r * 65536 + g * 256 + b end

local function pastel(r, g, b)
  return hex((r + 510) // 3, (g + 510) // 3, (b + 510) // 3)
end

local function dim(c, lv)
  local v = c * lv // 255
  if v < 0 then return 0 end
  if v > 255 then return 255 end
  return v
end

-- 0..100, integer: floats would reach set_pos and led.set, which want ints.
local function breath(now, p)
  local v = (now % p) * 200 // p
  if v > 100 then v = 200 - v end
  return v
end

local function stage_of(n)
  local s = 0
  for i = 1, #C.AT do
    if n >= C.AT[i] then s = i else break end
  end
  return s
end

-- ONE contact per call. Bytes in bulk, never string.byte in a loop.
local function scan_one()
  local c = badge.contacts.get(P.i)
  if not c then return false end
  S.total = P.i
  local id = c.badge_id
  if type(id) ~= "string" then id = tostring(id) end
  local h = 5381 + #id
  -- Six bytes from both ends is enough: h only feeds P.fold, and P.fold only
  -- picks a coat hue out of 46. It stopped needing to separate individual
  -- contacts when the hash ring was removed and strokes took their colours
  -- from C.ART instead.
  local a, b, d = string.byte(id, 1, 3)
  h = (h * 33 + (a or 1)) % 16777213
  h = (h * 33 + (b or 2)) % 16777213
  h = (h * 33 + (d or 3)) % 16777213
  a, b, d = string.byte(id, #id - 2, #id)
  h = (h * 33 + (a or 4)) % 16777213
  h = (h * 33 + (b or 5)) % 16777213
  h = (h * 33 + (d or 6)) % 16777213
  P.fold = (P.fold * 33 + h) % 16777213
  local slot = (P.i - 1) % 16 + 1
  local nm = "?"
  if type(c.name) == "string" then
    nm = string.sub(c.name, 1, 16)
    S.newest = c.name
  end
  S.nm[slot] = nm
  P.i = P.i + 1
  return true
end

-- Sizes and base positions, computed once per rebuild so that draw() only
-- has to add the bob offset.
local function meta()
  S.stage = stage_of(S.total)
  -- The stroke budget was decided when the scan finished, before any widget
  -- was made. Four per contact until the heap runs out, then it plateaus:
  -- below the cap every new friend adds four strokes, above it the painting
  -- is full and growth shows in the animal, the counter and the banner.
  local k, n = P.k, P.n
  -- Past C.MAXS strokes the painting covers the most RECENT contacts, not
  -- the first: the name ring holds the last 16, so painting from the front
  -- would name a different person from the one the strokes belong to.
  -- poff indexes strokes, base indexes the contact book.
  local cn = n // k
  local sel = cn
  if sel > 16 then sel = 16 end
  S.sel = sel
  S.poff = cn - sel
  S.base = S.total - sel

  -- Warm coats only. A free hue lands on magenta about as often as anything
  -- else, and the backdrops are cool, so the animal has to stay on the other
  -- side of the wheel to read as an animal rather than a smudge.
  S.pr, S.pg, S.pb = 255, 190, 90
  if S.total > 0 then S.pr, S.pg, S.pb = hue(P.fold % 46 + 12) end

  local hd = 64 + S.stage * 2          -- head width drives everything
  local hh = hd * 7 // 8
  L.hd, L.hh = hd, hh
  L.hx = 160 - hd // 2
  L.hy = 150 - hh
  L.bw = hd * 14 // 17
  L.bh = hd * 12 // 17
  L.bx = 160 - L.bw // 2
  L.by = 142
  L.blw = hd * 8 // 17
  L.blh = L.bh * 2 // 3
  L.blx = 160 - L.blw // 2
  L.bly = L.by + L.bh - L.blh - 2

  local sp = C.SP[S.species]
  L.ew = hd * sp[2] // 34
  L.eh = hd * sp[3] // 34
  L.er = L.ew // 2
  if sp[4] < 10 then L.er = L.ew // 3 end
  local spread = hd * sp[5] // 34
  L.elx = 160 - spread - L.ew // 2
  L.erx = 160 + spread - L.ew // 2
  L.ey = L.hy - L.eh + L.eh // 3
  L.iw = L.ew // 2
  L.ih = L.eh * 3 // 5

  L.ed = hd * 7 // 34                  -- eye width
  L.eyh = hd * 9 // 34                 -- eye height, taller than wide
  L.elex = 160 - hd // 5 - L.ed // 2
  L.erex = 160 + hd // 5 - L.ed // 2
  L.eyy = L.hy + hh // 2 - L.eyh // 3
  L.gd = hd * 5 // 68                  -- the highlight that gives it life
  L.nw = hd * 2 // 17
  L.nx = 160 - L.nw // 2
  L.ny = L.eyy + L.eyh + hd // 17
  L.bld = hd * 5 // 24                 -- blush
  L.blh2 = L.bld * 3 // 5
  L.td = hd * sp[6] // 34
  L.tx = 160 + L.bw // 2 - L.td // 3
  L.ty = L.by + L.bh // 4
  L.fd = hd * 5 // 17
  L.fh = L.fd * 2 // 3
  L.flx = 160 - L.bw // 4 - L.fd // 2
  L.frx = 160 + L.bw // 4 - L.fd // 2
  L.fy = L.by + L.bh - L.fh // 2

  -- Stroke diameter keeps about half the canvas covered at any count.
  local d = 8
  if n > 0 then d = math.floor(2 * math.sqrt(13445 / n)) end
  if d < 8 then d = 8 end
  if d > 58 then d = 58 end
  L.sd = d
end

-- Paint strokes lo..hi. Positions come from the R2 low-discrepancy sequence,
-- so every stroke lands in the largest remaining gap and the canvas looks
-- evenly covered at any count, with nothing rearranging as it grows.
-- Colours are baked per stroke index by tools/artgen.py.
local function paint(lo, hi)
  for i = lo, hi do
    if i <= P.n then
      local h = (i * 2654435761) % 4294967296
      local d = L.sd * (78 + (h // 524288) % 45) // 100
      local x = math.floor(((0.5 + 0.7548776662 * i) % 1) * 320) + (h // 8) % 9 - 4
      local y = math.floor(((0.5 + 0.5698402910 * i) % 1) * 240) + (h // 2048) % 9 - 4
      if x < -10 then x = -10 end
      if x > 318 then x = 318 end
      if y < -10 then y = -10 end
      if y > 234 then y = 234 end
      G[i]:set_size(d, d)
      G[i]:style({radius = d // 2, border_width = 0,
                  bg_color = C.PAL[string.byte(C.ART, i) - 64] or C.BG})
      G[i]:set_pos(x, y)
      G[i]:hidden(false)
    elseif G[i] then
      G[i]:hidden(true)
    end
  end
end

-- One function, three branches: three separate locals would each cost a
-- main-chunk slot, and the main chunk is the tightest budget in the file.
-- One function, three branches: three separate locals would each cost a
-- main-chunk slot, and the main chunk is the tightest budget in the file.
local function dress(part)
  local coat = hex(S.pr, S.pg, S.pb)
  local soft = pastel(S.pr, S.pg, S.pb)
  local pw = C.pw
  if part == 1 then
    pw("egg", 68, 86, 0xf0e6d2, 34)
    pw("body", L.bw, L.bh, coat, L.bh // 2)
    pw("belly", L.blw, L.blh, soft, L.blh // 2)
    pw("head", L.hd, L.hh, coat, L.hh // 2)
    pw("tail", L.td, L.td, coat, L.td // 2)
    pw("tailT", L.td // 2, L.td // 2, soft, L.td // 4)
  elseif part == 2 then
    pw("earL", L.ew, L.eh, coat, L.er)
    pw("earR", L.ew, L.eh, coat, L.er)
    pw("einL", L.iw, L.ih, 0xffb9c6, L.iw // 2)
    pw("einR", L.iw, L.ih, 0xffb9c6, L.iw // 2)
    pw("footL", L.fd, L.fh, soft, L.fh // 2)
    pw("footR", L.fd, L.fh, soft, L.fh // 2)
  else
    pw("eyeL", L.ed, L.eyh, 0x241c18, L.ed // 2)
    pw("eyeR", L.ed, L.eyh, 0x241c18, L.ed // 2)
    pw("glL", L.gd, L.gd, 0xffffff, L.gd // 2)
    pw("glR", L.gd, L.gd, 0xffffff, L.gd // 2)
    pw("nose", L.nw, L.nw * 3 // 4, 0x3a2a22, L.nw // 2)
    pw("blL", L.bld, L.blh2, 0xff8fa3, L.blh2 // 2)
    pw("blR", L.bld, L.blh2, 0xff8fa3, L.blh2 // 2)
    W.blL:style({bg_opa = 150})
    W.blR:style({bg_opa = 150})
    W.mouth:style({line_color = 0x3a2a22, line_width = 2})
  end
end

-- The one line under the pet. Three states, so no caller duplicates these
-- strings: egg, a picked contact, or the default summary.
local function stat_line()
  if S.egg then
    if S.total > 0 then
      return S.total .. " friends waiting.  Bump one to hatch."
    end
    return "Open Connect and bump a badge to hatch"
  end
  if S.cur > 0 then
    local idx = S.base + S.cur
    return "#" .. idx .. "  " .. (S.nm[(idx - 1) % 16 + 1] or "?")
  end
  -- Say what the leds are waiting for. B already works below the threshold
  -- -- it toggles the coat glow -- so the thing that unlocks is the stars,
  -- and calling it "lights" would be wrong.
  -- Two spaces, not three: at font 16 the longest form of this line is
  -- about 272px of the 320 available, and three spaces pushes it to 296.
  local t = S.total .. " friends  " .. P.n .. " strokes"
  if S.total < C.STAR then t = t .. "  stars at " .. C.STAR end
  return t
end

local function finish()
  W.egg:hidden(not S.egg)
  for i = 2, #C.MK do W[C.MK[i]]:hidden(S.egg) end
  W.mouth:hidden(S.egg)
  W.prog:hidden(S.egg)
  if S.egg then
    W.title:set_text(S.petname .. "  the  egg")
  else
    W.title:set_text(S.petname .. "  the  " .. C.SP[S.species][1])
  end
  W.stat:set_text(stat_line())
  local lo = C.AT[S.stage] or 0
  local hi = C.AT[S.stage + 1]
  local p = 100
  if hi and hi > lo then p = (S.total - lo) * 100 // (hi - lo) end
  if p < 0 then p = 0 end
  if p > 100 then p = 100 end
  W.prog:set_value(p)
end

-- Attribution. Left/Right walk the contacts; the strokes that contact painted
-- get a white outline and the line underneath names them. This is what makes
-- the backdrop a portrait rather than wallpaper.
local function pick(d)
  if S.egg or S.sel == 0 then return end
  local old = S.cur
  local c = old + d
  if c > S.sel then c = 0 elseif c < 0 then c = S.sel end
  S.cur = c
  for j = 1, 2 do
    local w = j == 1 and old or c
    if w > 0 and w <= S.sel then
      for i = (S.poff + w - 1) * P.k + 1, (S.poff + w) * P.k do
        if i <= P.n then
          G[i]:style({border_color = 0xffffff, border_width = j == 1 and 0 or 2})
        end
      end
    end
  end
  W.stat:set_text(stat_line())
end

local function draw(now)
  if S.egg then
    W.egg:set_pos(126, 52 + 6 * breath(now, 2600) // 100)
    return
  end
  -- gentle bob; the head lags by half a beat so it reads as breathing
  local b = breath(now, 2400)
  local dy = (b - 50) * 5 // 100
  local hdy = (breath(now + 300, 2400) - 50) * 6 // 100

  W.body:set_pos(L.bx, L.by + dy)
  W.belly:set_pos(L.blx, L.bly + dy)
  W.tail:set_pos(L.tx, L.ty + dy)
  W.tailT:set_pos(L.tx + L.td // 2, L.ty + dy + L.td // 4)
  W.head:set_pos(L.hx, L.hy + hdy)
  W.earL:set_pos(L.elx, L.ey + hdy)
  W.earR:set_pos(L.erx, L.ey + hdy)
  W.einL:set_pos(L.elx + L.iw // 2, L.ey + hdy + L.eh // 4)
  W.einR:set_pos(L.erx + L.iw // 2, L.ey + hdy + L.eh // 4)
  W.eyeL:set_pos(L.elex, L.eyy + hdy)
  W.eyeR:set_pos(L.erex, L.eyy + hdy)
  W.glL:set_pos(L.elex + L.gd // 2, L.eyy + hdy + L.gd // 2)
  W.glR:set_pos(L.erex + L.gd // 2, L.eyy + hdy + L.gd // 2)
  W.blL:set_pos(L.elex - L.bld // 2, L.eyy + hdy + L.eyh)
  W.blR:set_pos(L.erex + L.ed - L.bld // 2, L.eyy + hdy + L.eyh)
  W.nose:set_pos(L.nx, L.ny + hdy)
  W.mouth:set_pos(L.nx - 8, L.ny + hdy + L.nw)
  W.footL:set_pos(L.flx, L.fy)
  W.footR:set_pos(L.frx, L.fy)

  local shut = (now % 3600) < 130
  if shut ~= S.blink then
    S.blink = shut
    local h = L.eyh
    if shut then h = 2 end
    W.eyeL:set_size(L.ed, h)
    W.eyeR:set_size(L.ed, h)
    W.glL:hidden(shut)
    W.glR:hidden(shut)
  end
end

local function leds(now)
  badge.led.clear()
  if not S.led then
    badge.led.show()
    return
  end
  local lv = S.lv
  if S.celeb > now then
    local st = now // 80 % 6
    for i = 1, 6 do
      local q = lv - ((i - 1 - st) % 6) * 34
      if q < 0 then q = 0 end
      badge.led.set(C.CW[i], dim(S.pr, q), dim(S.pg, q), dim(S.pb, q))
    end
  elseif S.egg then
    -- The egg is the front door: every badge starts here, and it is the
    -- "come bump me" signal. All six, breathing 35..100% of brightness.
    -- Two leds at 15..50% read as off once the firmware curve is applied.
    local q = lv * (3500 + 65 * breath(now, 3000)) // 10000
    for i = 1, 6 do
      badge.led.set(C.CW[i], q, dim(180, q), dim(70, q))
    end
  elseif S.total >= C.STAR then
    -- Starfield, to match the sky the contacts are painting. Each led runs
    -- its own period and offset so they never pulse together the way one
    -- shared breath does, and the square makes the brightening sharp rather
    -- than a slow fade, which is what reads as a twinkle. The offsets are
    -- squared because evenly spaced ones make the six ramp in order, which
    -- reads as a wave travelling round the badge instead of as stars.
    -- Peak is 63% of brightness rather than 88%: at full it read as harsh
    -- rather than as a night sky. The floor stays near black so a star can
    -- go out. Periods are long for the same reason - fast twinkling is
    -- agitated, and this sits behind everything else on the badge.
    for i = 1, 6 do
      local b = breath(now + i * i * 631 % 2600, 2100 + i * 310)
      local q = lv * (8 + b * b // 180) // 100
      badge.led.set(C.CW[i], dim(190, q), dim(215, q), q)
    end
  else
    -- Coat 20..45%, with one travelling highlight at full brightness. Below
    -- about 20% the coat reads as black and only the highlight is visible.
    local q = lv * (2000 + 25 * breath(now, 2400)) // 10000
    for i = 1, 6 do
      badge.led.set(C.CW[i], dim(S.pr, q), dim(S.pg, q), dim(S.pb, q))
    end
    local tr = 900 - S.stage * 40
    if tr < 260 then tr = 260 end
    badge.led.set(C.CW[now // tr % 6 + 1],
                  dim(S.pr, lv), dim(S.pg, lv), dim(S.pb, lv))
  end
  badge.led.show()
end

-- ONE bounded unit of work. Never chain two steps in a single tick.
-- Strokes are created before the creature so the creature draws in front of
-- them: LVGL stacks children in creation order and there is no z-index.
local function step(now)
  local s = P.step
  if s == 1 then
    S.led = badge.store.get_int("led_on", 1) ~= 0
    S.lv = badge.store.get_int("led_lv", 170)
    S.seen = badge.store.get_int("seen", -1)
    S.hatch = badge.store.get_int("hatch", -1)
    P.step = 2
  elseif s == 2 then
    local id = badge.me.badge_id()
    if type(id) == "string" then
      S.petname = string.upper(string.match(id, "^[^-]+") or id)
      -- Species is YOURS and never changes. Deriving it from the contact
      -- fold instead would turn you into a different animal every time you
      -- met someone, which is no way to get attached to a pet. Sampled from
      -- both ends of the id because word slugs share their separators.
      local a, b, d, e = string.byte(id, 1, 4)
      local f, g = string.byte(id, #id - 1, #id)
      S.species = ((a or 1) * 7 + (b or 2) * 13 + (d or 3) * 31
                   + (e or 5) * 57 + (f or 7) * 91 + (g or 11)) % 4 + 1
    end
    P.step = 3
  elseif s == 3 then
    if P.i > C.SCAN or not scan_one() then
      -- Contacts cannot change while this app is in the foreground, because
      -- bumping means leaving it. So the stroke count is known now, and the
      -- widgets can be sized to it rather than always allocating C.MAXS and
      -- hiding the difference. Hiding a widget does not free it.
      if S.hatch < 0 then
        S.hatch = S.total
        S.dirty = true
      end
      S.egg = S.total <= S.hatch
      -- Paint what the heap can afford, not a fixed number. Each widget
      -- costs about 112 bytes of system heap, and a badge with other apps
      -- on it has less than this one -- which is every badge this app gets
      -- shared to. A count tuned here would fail there.
      --
      -- The reserve is 6000, not 14000. 14000 was a guess, and it was wrong
      -- in the worst way: on a badge reporting less than that the cap went
      -- to zero and the painting disappeared entirely, with a creature and
      -- an empty sky. A degradation path that degrades to nothing is not a
      -- degradation path.
      --
      -- C.MINS strokes are painted whatever the heap says. The previous
      -- build ran 148 widgets down to 2.2 KB free, so the floor costs less
      -- than a badge that cannot afford it would survive anyway, and having
      -- a painting at all matters more than the last kilobyte.
      local free = badge.sys.stats().free_heap
      local cap = (free - 6000) // 112
      if cap > C.MAXS then cap = C.MAXS end
      if cap < C.MINS then cap = C.MINS end
      -- Two strokes per contact, not four. Four fills the canvas faster
      -- but hits the heap cap at half the contact count, and plateauing
      -- at thirteen friends is worse than a sparser start.
      local n = S.total * 2
      if n > cap then n = cap end
      badge.sys.log("paint free=" .. free .. " cap=" .. cap .. " n=" .. n)
      if S.egg then n = 0 end
      P.n = n
      local k = 1
      if S.total > 0 then k = n // S.total end
      if k < 1 then k = 1 end
      P.k = k
      if P.made then P.step = 40 else P.step = 4 end
    end
  elseif s >= 4 and s <= 18 then
    local base = (s - 4) * 8
    for i = base + 1, base + 8 do
      if i <= P.n then
        G[i] = badge.ui.box(W.bg, 8, 8)
        G[i]:hidden(true)
      end
    end
    if base + 8 >= P.n then P.step = 19 else P.step = s + 1 end
  elseif s >= 19 and s <= 23 then
    local base = (s - 19) * 4
    for i = base + 1, base + 4 do
      local n = C.MK[i]
      if n then
        W[n] = badge.ui.box(W.bg, 8, 8)
        W[n]:hidden(true)
      end
    end
    P.step = s + 1
  elseif s == 24 then
    W.mouth = badge.ui.line(W.bg, {{0, 0}, {4, 4}, {8, 0}, {12, 4}, {16, 0}})
    W.mouth:hidden(true)
    W.title = badge.ui.label(W.bg, "")
    W.title:style({text_font = 20, text_color = 0xffd45e})
    W.title:align("top_mid", 0, 6)
    W.stat = badge.ui.label(W.bg, "")
    P.step = 25
  elseif s == 25 then
    W.stat:style({text_font = 16, text_color = 0xe6eef7})
    W.stat:align("bottom_mid", 0, -30)
    W.prog = badge.ui.bar(W.bg, 0, 100, 0)
    W.prog:set_size(236, 6)
    P.step = 26
  elseif s == 26 then
    W.prog:set_pos(42, 214)
    W.prog:style({bg_color = 0x1d2733, radius = 3})
    W.banner = badge.ui.label(W.bg, "")
    W.banner:style({text_font = 18, text_color = 0xffd45e})
    P.step = 27
  elseif s == 27 then
    W.banner:align("top_mid", 0, 34)
    W.banner:hidden(true)
    W.hint = badge.ui.label(W.bg, "L/R who is who   A rescan   B lights")
    P.step = 28
  elseif s == 28 then
    W.hint:style({text_font = 14, text_color = 0x8ea0b4})
    W.hint:align("bottom_mid", 0, -8)
    W.boot:hidden(true)
    P.made = true
    P.step = 40
  elseif s == 40 then
    meta()
    P.step = 41
  elseif s >= 41 and s <= 55 then
    paint((s - 41) * 8 + 1, (s - 41) * 8 + 8)
    P.step = s + 1
  elseif s >= 56 and s <= 58 then
    dress(s - 55)
    P.step = s + 1
  elseif s == 59 then
    finish()
    P.step = 60
  else
    if S.seen >= 0 and S.total > S.seen then
      if S.seen <= S.hatch and not S.egg then
        W.banner:set_text("HATCHED")
      elseif S.stage > stage_of(S.seen) then
        W.banner:set_text("EVOLVED   stage " .. S.stage)
      else
        W.banner:set_text("NEW FRIEND   " .. string.sub(S.newest, 1, 14))
      end
      W.banner:hidden(false)
      S.celeb = now + 2600
      -- The strokes the new contacts painted are the last ones, because the
      -- painting follows the most recent contacts. Marking them says "these
      -- are the person you just met", which is the same claim attribution
      -- makes, at the moment it means most.
      local lo = (S.seen - S.total + P.n // P.k) * P.k + 1
      if lo < 1 then lo = 1 end
      S.nlo = lo
    end
    if S.seen ~= S.total then
      S.seen = S.total
      S.dirty = true
    end
    S.nextf = now
    P.step = 0
  end
end

function on_enter(root)
  W.bg = badge.ui.box(root, 320, 240)
  W.bg:set_pos(0, 0)
  W.bg:style({bg_color = C.BG, border_width = 0, radius = 0})
  W.boot = badge.ui.label(W.bg, "waking up...")
  W.boot:style({text_font = 20, text_color = 0x5d6f80})
  W.boot:align("center", 0, 0)
end

function on_tick()
  local now = badge.sys.ms()
  if P.step > 0 then
    step(now)
    return
  end
  if now < S.nextf then return end
  S.nextf = now + 50
  if S.celeb > 0 and now >= S.celeb then
    W.banner:hidden(true)
    S.celeb = 0
  end
  if S.nlo > 0 then
    local on = 0
    if S.celeb > now and now // 260 % 2 == 1 then on = 2 end
    if on ~= S.npul then
      S.npul = on
      for i = S.nlo, P.n do
        G[i]:style({border_color = 0xffffff, border_width = on})
      end
    end
    if S.celeb == 0 then S.nlo = 0 end
  end
  draw(now)
  leds(now)
end

function on_button(button, kind)
  if kind ~= badge.input.KIND.PRESSED then return end
  if P.step > 0 then return end
  local B = badge.input.BUTTON
  if button == B.A then
    P.i, P.fold = 1, 7
    S.total, S.cur = 0, 0
    P.step = 3
    return
  elseif button == B.LEFT then
    pick(-1)
    return
  elseif button == B.RIGHT then
    pick(1)
    return
  elseif button == B.B then
    S.led = not S.led
    S.dirty = true
  elseif button == B.UP then
    S.lv = math.min(255, S.lv + 24)
    S.dirty = true
  elseif button == B.DOWN then
    S.lv = math.max(24, S.lv - 24)
    S.dirty = true
  else
    return
  end
  leds(badge.sys.ms())
end

function on_exit()
  badge.led.clear()
  badge.led.show()
  if S.dirty then
    badge.store.set_int("seen", S.seen)
    badge.store.set_int("hatch", S.hatch)
    badge.store.set_int("led_on", S.led and 1 or 0)
    badge.store.set_int("led_lv", S.lv)
  end
end
