"""Turn a background image into the two constants the badge ships.

    python3 tools/artgen.py art/night.png

Prints a Lua snippet: a palette, and one character per stroke naming that
stroke's colour.

The badge never sees the image. Stroke positions are deterministic (the R2
low-discrepancy sequence), so their colours can be baked at build time and
looked up with a single string.byte. That costs a few hundred bytes of source
against the several kilobytes an image would need, and the compile-memory
ceiling is spent on source bytes.
"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from paintmock import prepare, A1, A2, W, H   # noqa: E402

MAXS = 120       # strokes the app will ever draw
FIRST = 65       # 'A'; palette index = byte - 64


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "art/night.png"
    img = prepare(path)
    px = img.load()

    # The quantised image has few colours; collect them in first-seen order
    # so the palette is exactly what the strokes need and nothing more.
    palette, index = [], {}
    codes = []
    for i in range(1, MAXS + 1):
        x = ((0.5 + A1 * i) % 1.0) * W
        y = ((0.5 + A2 * i) % 1.0) * H
        h = (i * 2654435761) & 0xFFFFFFFF
        x += ((h >> 3) % 9) - 4
        y += ((h >> 11) % 9) - 4
        cx = min(W - 1, max(0, int(x)))
        cy = min(H - 1, max(0, int(y)))
        rgb = px[cx, cy]
        if rgb not in index:
            index[rgb] = len(palette)
            palette.append(rgb)
        codes.append(chr(FIRST + index[rgb]))

    if len(palette) > 26:
        sys.stderr.write(f"palette of {len(palette)} exceeds 26\n")
        return 1

    pal = ", ".join("0x%02x%02x%02x" % c for c in palette)
    art = "".join(codes)

    print(f"-- generated by tools/artgen.py from {os.path.basename(path)}")
    print(f"-- {len(palette)} colours, {MAXS} strokes")
    print("C.PAL = {" + pal + "}")
    print(f'C.ART = "{art}"')
    print()
    sys.stderr.write(
        f"{len(palette)} colours, {MAXS} strokes, "
        f"{len(pal) + len(art) + 24} bytes of Lua\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
